NETWORK_PARAMS:
  L0: 5
  Q: 3
  hidden_features: 20
  out_features: 1
  activation: "sin"  

TRAINING_PARAMS:
  epochs: 200
  batch_size: 128
  device: "cpu"

EXPERIMENT_PARAMS:
  N : 1000
  n_run : 5
  lmax : 20
  lr : 0.001
  target: "cartoon_shape"
  results_path : "results/"