NETWORK_PARAMS:
  L0: 5
  Q: 2
  hidden_features: 20
  out_features: 1
  activation: "sinh"  

TRAINING_PARAMS:
  epochs: 1000
  batch_size: 128
  device: "cpu"

EXPERIMENT_PARAMS:
  N : 200
  n_run : 5
  lmax : 20
  lr : 0.001
  target: "cartoon_shape"
  results_path : "./results/"
