NETWORK_PARAMS:
  L0: 5
  Q: 3
  hidden_features: 40
  out_features: 1
  activation: "sin"  

TRAINING_PARAMS:
  epochs: 200
  batch_size: 128
  device: "cpu"
  lr: 0.001

EXPERIMENT_PARAMS:
  N : 1000
  lmax : 30
  model_path : "model/"
  results_path : "results/"
  target : "cartoon_shape"
    
